sudo: false
language: node_js

node_js:
  - "6.2"

os:
  - osx
  - linux
    
install:
  - node --version
  - npm --version
  - npm install

script:
  - echo Compiling...
  - node ./node_modules/vscode/bin/compile
  - echo Compiled
